services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
#      interval: 15s
#      timeout: 10s
#      retries: 15
#      start_period: 120s
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: ${CONTAINER_TEST_IMAGE}
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3308/cicd
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy
volumes:
  mysql-data: